# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://ggoggama.leeseungju.com
title: 꽃가마 장례서비스
email: tace0701@gmail.com
author: 김기복
description: # "Write an awesome description for your new site here. 
  꽃가마 장례서비스, 장례지도사/부사장 김기복. 상담:010-9313-6756 귀하게 모시겠습니다.
  
copyright: 'Copyright &copy; 2019 leeseungju. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: 전화
    url: tel:010-9313-6756
  - title: 문자
    url: sms:010-9313-6756
